<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Rating extends Model
{
    /**
     * Make primary key non-increment
     * @var bool
     */
 //   public $incrementing = false;

//    protected $primaryKey = array('entity_id', 'entity_type_id', 'rating_type_id');

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'entity_id',
        'entity_type_id',
        'rate',
        'rating_type_id'
    ];

    public static function insert($newRating)
    {
        return self::create($newRating);
    }

    public static function fetch($ratingData)
    {
        $rating = self::where('entity_id', $ratingData['entity_id'])
            ->where('entity_type_id', $ratingData['entity_type_id'])
            ->where('rating_type_id', $ratingData['rating_type_id'])
            ->first();

        return $rating;
    }

    public static function updateRate($ratingData)
    {
         $result = self::where('entity_id', $ratingData['entity_id'])
            ->where('entity_type_id', $ratingData['entity_type_id'])
            ->where('rating_type_id', $ratingData['rating_type_id'])
            ->update(['rate' => $ratingData['rate']]);

         return $result;

    }


    public static function updateOrInsert($ratingData, $updateData = [])
    {

        $rating = self::updateOrCreate($ratingData, $updateData);

        return $rating;
    }

    public static function deleteRatings($condition)
    {
        return self::whereRaw($condition)->delete(); // TODO: Change the autogenerated stub
    }


}
